#pragma once
#include <afx.h>
#include <afxwin.h>
#include <afxdlgs.h>
#include <afxdialogex.h>
#include <fstream>
#include <iostream>
#include <string>
#include "SDL2/SDL.h"
#include "SDL2/SDL_opengl.h"
#include <GL/GLU.h>
#include "SDL2/glut.h"
#include <ctime>
#include <math.h>
#include <array>
#include <vector>